FROM fedora:38 as builder

RUN dnf install -y \
    git \
    unzip \
    swift-lang-5.7.3-2.fc38 \
    javascriptcoregtk4.0-devel \
    libatomic_ops

RUN ln -s /usr/libexec/swift/*/lib/libsourcekitdInProc.so /usr/lib/libsourcekitdInProc.so

WORKDIR /root/Flynn
COPY ./dist ./dist
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift build --configuration release

FROM fedora:38

WORKDIR /root/Flynn
COPY --from=builder /root/Flynn/.build/release/FlynnPluginTool-focal .
COPY --from=builder /root/Flynn/.build/release/FlynnPluginTool-focal .
