FROM swift:6.1.2-jammy as builder

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
    apt-get install -y \
    unzip

WORKDIR /root/Flynn
COPY ./dist ./dist
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift build --configuration release

FROM swift:jammy

WORKDIR /root/Flynn
COPY --from=builder /root/Flynn/.build/release/FlynnPluginTool .
COPY --from=builder /root/Flynn/.build/release/FlynnPluginTool .
