FROM swift:5.6.2-amazonlinux2

RUN yum install -y \
    unzip

WORKDIR /root/Flynn
COPY ./dist ./dist
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift build --configuration release
