FROM swift:5.9.2-amazonlinux2 as builder

RUN yum install -y \
    unzip

WORKDIR /root/Flynn
COPY ./dist ./dist
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift build --configuration release

FROM swift:focal

WORKDIR /root/Flynn
COPY --from=builder /root/Flynn/.build/release/FlynnPluginTool-focal .
COPY --from=builder /root/Flynn/.build/release/FlynnPluginTool-focal .
