import Flynn
import Foundation

public class RootCounter: Actor {
    private var total: Int = 0
    private var remotes: [RemoteCounter] = []

    public override init() {
        super.init()

        Flynn.Timer(timeInterval: 1.0, repeats: true, self) { (_) in
            self.total = 0

            let remoteCores = Flynn.remoteCores

            // send to all existing remotes (if a node drops, this
            // will clear their socket and allow unsafeIsConnected() to
            // know they are no longer connected
            for counter in self.remotes {
                counter.beIncrement(10, self) {
                    self.total += $0.withUnsafeBytes { $0.load(as: Int.self) }
                }
            }

            // remove any RemoteCounters who are no longer connected
            self.remotes.removeAll { $0.unsafeIsConnected() == false }

            // add or remove new remote counters until equal the number of remote cores
            while self.remotes.count > remoteCores {
                self.remotes.removeFirst()
            }
            while self.remotes.count < remoteCores {
                self.remotes.append(RemoteCounter())
            }

        }
    }

    private func _beGetTotal() -> Int {
        return total
    }

}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension RootCounter {

    @discardableResult
    public func beGetTotal(_ sender: Actor,
                           _ callback: @escaping ((Int) -> Void)) -> Self {
        unsafeSend {
            let result = self._beGetTotal()
            sender.unsafeSend { callback(result) }
        }
        return self
    }

}
