//
//  main.swift
//  flynnlint
//
//  Created by Rocco Bowling on 5/29/20.
//  Copyright © 2020 Rocco Bowling. All rights reserved.
//

import Foundation
import Flynn

class FindFiles: Actor, Flowable {
    // input: path to source directory
    // output: paths to individual swift files
    var safeFlowable = FlowableState()
    private let extensions: [String]
    
    var filesProcessed:[String:Bool] = [:]

    init (_ extensions: [String]) {
        self.extensions = extensions
    }

    private func _beFlow(_ args: FlowableArgs) {
        if args.isEmpty { return self.safeFlowToNextTarget(args) }

        let output: String = args[x:0]
        let source: String = args[x:1]
        
        
        try! FileManager.default.createDirectory(at: URL(fileURLWithPath: output),
                                                 withIntermediateDirectories: true)
        
        do {
            let resourceKeys: [URLResourceKey] = [.creationDateKey, .isDirectoryKey]
            let enumerator = FileManager.default.enumerator(at: URL(fileURLWithPath: source),
                                                            includingPropertiesForKeys: resourceKeys,
                                                            options: [.skipsHiddenFiles],
                                                            errorHandler: { (url, error) -> Bool in
                                                                print("directoryEnumerator error at \(url): ", error)
                                                                return true
            })!

            for case let fileURL as URL in enumerator {
                let resourceValues = try fileURL.resourceValues(forKeys: Set(resourceKeys))
                let pathExtension = (fileURL.path as NSString).pathExtension
                if self.extensions.contains(pathExtension) && resourceValues.isDirectory == false {
                    // safeguard that we do not process the same file twice
                    if filesProcessed[fileURL.path] == nil {
                        filesProcessed[fileURL.path] = true
                        self.safeFlowToNextTarget([output, source, fileURL.path])
                    }
                }
            }
        } catch {
            print(error)
        }
    }

}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension FindFiles {

    @discardableResult
    public func beFlow(_ args: FlowableArgs) -> Self {
        unsafeSend { self._beFlow(args) }
        return self
    }

}
