import Flynn
import Foundation
import LzSwift

public class RemoteCompressor: RemoteActor {

    private let compressor = Lzip.Compress(level: .lvl6)
    private var compressed = Data()

    private func _beArchive(_ data: Data) -> Bool {
        do {
            try compressor.compress(input: data, output: &compressed)
        } catch {
            return false
        }
        return true
    }

    private func _beFinish() -> Data {
        compressor.finish(output: &compressed)
        return compressed
    }
}

public class RemoteDecompressor: RemoteActor {

    private let decompressor = Lzip.Decompress()
    private var decompressed = Data()

    private func _beArchive(_ data: Data) -> Bool {
        do {
            try decompressor.decompress(input: data, output: &decompressed)
        } catch {
            return false
        }
        return true
    }

    private func _beFinish() -> Data {
        decompressor.finish(output: &decompressed)
        return decompressed
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension RemoteDecompressor {

    struct BeArchiveCodableResponse: Codable {
        let response: Bool
    }
    struct BeArchiveCodableRequest: Codable {
        let arg0: Data
    }
    struct BeFinishCodableResponse: Codable {
        let response: Data
    }

    @discardableResult
    public func beArchive(_ data: Data,
                          _ sender: Actor,
                          _ callback: @escaping (Bool) -> Void ) -> Self {
        let msg = BeArchiveCodableRequest(arg0: data)
        // swiftlint:disable:next force_try
        let data = try! JSONEncoder().encode(msg)
        unsafeSendToRemote("RemoteDecompressor", "beArchive", data, sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! JSONDecoder().decode(BeArchiveCodableResponse.self, from: $0).response)
            )
        }
        return self
    }
    @discardableResult
    public func beFinish(_ sender: Actor, _ callback: @escaping (Data) -> Void) -> Self {
        unsafeSendToRemote("RemoteDecompressor", "beFinish", Data(), sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! JSONDecoder().decode(BeFinishCodableResponse.self, from: $0)).response
            )
        }
        return self
    }

    public func unsafeRegisterAllBehaviors() {
        safeRegisterRemoteBehavior("beArchive") { [unowned self] (data) in
            // swiftlint:disable:next force_try
            let msg = try! JSONDecoder().decode(BeArchiveCodableRequest.self, from: data)
            let response = self._beArchive(msg.arg0)
            let boxedResponse = BeArchiveCodableResponse(response: response)
            // swiftlint:disable:next force_try
            return try! JSONEncoder().encode(boxedResponse)
        }
        safeRegisterRemoteBehavior("beFinish") { [unowned self] (_) in
            // swiftlint:disable:next force_try
            return try! JSONEncoder().encode(
                BeFinishCodableResponse(response: self._beFinish()))
        }
    }
}

extension RemoteCompressor {

    struct BeArchiveCodableResponse: Codable {
        let response: Bool
    }
    struct BeArchiveCodableRequest: Codable {
        let arg0: Data
    }
    struct BeFinishCodableResponse: Codable {
        let response: Data
    }

    @discardableResult
    public func beArchive(_ data: Data,
                          _ sender: Actor,
                          _ callback: @escaping (Bool) -> Void ) -> Self {
        let msg = BeArchiveCodableRequest(arg0: data)
        // swiftlint:disable:next force_try
        let data = try! JSONEncoder().encode(msg)
        unsafeSendToRemote("RemoteCompressor", "beArchive", data, sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! JSONDecoder().decode(BeArchiveCodableResponse.self, from: $0).response)
            )
        }
        return self
    }
    @discardableResult
    public func beFinish(_ sender: Actor, _ callback: @escaping (Data) -> Void) -> Self {
        unsafeSendToRemote("RemoteCompressor", "beFinish", Data(), sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! JSONDecoder().decode(BeFinishCodableResponse.self, from: $0)).response
            )
        }
        return self
    }

    public func unsafeRegisterAllBehaviors() {
        safeRegisterRemoteBehavior("beArchive") { [unowned self] (data) in
            // swiftlint:disable:next force_try
            let msg = try! JSONDecoder().decode(BeArchiveCodableRequest.self, from: data)
            let response = self._beArchive(msg.arg0)
            let boxedResponse = BeArchiveCodableResponse(response: response)
            // swiftlint:disable:next force_try
            return try! JSONEncoder().encode(boxedResponse)
        }
        safeRegisterRemoteBehavior("beFinish") { [unowned self] (_) in
            // swiftlint:disable:next force_try
            return try! JSONEncoder().encode(
                BeFinishCodableResponse(response: self._beFinish()))
        }
    }
}
