import Flynn

class HelloWorld: Actor {

    private func _bePrint1(_ string: String) {
        print("1: \(string)")
    }

    private func _bePrint2(_ string: String) {
        print("2: \(string)")
    }

}

print("before")
HelloWorld().bePrint1("Hello").bePrint2("Goodbye")
print("after")

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension HelloWorld {

    @discardableResult
    public func bePrint1(_ string: String) -> Self {
        unsafeSend { self._bePrint1(string) }
        return self
    }
    @discardableResult
    public func bePrint2(_ string: String) -> Self {
        unsafeSend { self._bePrint2(string) }
        return self
    }

}
