import Flynn

class HelloWorld: Actor {
    private func _bePrint(_ string: String) {
        print(string)
    }
}

print("synchronous: before")
HelloWorld().bePrint("asynchronous: hello world")
print("synchronous: after")

Flynn.shutdown()

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension HelloWorld {

    @discardableResult
    public func bePrint(_ string: String) -> Self {
        unsafeSend { self._bePrint(string) }
        return self
    }

}
