import XCTest
@testable import Flynn

class Echo: RemoteActor {
    private let echoUUID = UUID().uuidString
    private var count: Int = 999

    override func safeInit() {
        count = 0
    }

    private func _bePrintThreadName() -> Int {
        if let name = Thread.current.name {
            sleep(1)
            print("Echo running on \(name)")
        }
        return 0
    }

    private func _bePrint(_ string: String) {
        print("on node: '\(string)'")
    }

    private func _beToLower(_ string: String) -> String {
        count += 1
        return "\(string) [\(count)]".lowercased()
    }

    private func _beTestDelayedReturn(_ string: String, _ returnCallback: @escaping (String) -> Void) {
        Flynn.Timer(timeInterval: Double.random(in: 0..<3), repeats: false, safeActor) { (_) in
            returnCallback(string.uppercased())
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

import BinaryCodable

extension Echo {

    struct BePrintThreadNameCodableResponse: BinaryEncodable, BinaryDecodable {
        let response: Int

        init(response: Int) {
            self.response = response
        }

        func encode(to encoder: BinaryEncoder) throws {
            var container = encoder.container()
            try container.encode(response)
        }

        init(from decoder: BinaryDecoder) throws {
            var container = decoder.container(maxLength: nil)
            response = try container.decode(Int.self)
        }
    }
    struct BePrintCodableRequest: BinaryEncodable, BinaryDecodable {
        let arg0: String

        init(arg0: String) {
            self.arg0 = arg0
        }

        func encode(to encoder: BinaryEncoder) throws {
            var container = encoder.container()
            try container.encode(arg0, encoding: .utf8, terminator: 0)
        }

        init(from decoder: BinaryDecoder) throws {
            var container = decoder.container(maxLength: nil)
            arg0 = try container.decodeString(encoding: .utf8, terminator: 0)
        }
    }
    struct BeToLowerCodableResponse: BinaryEncodable, BinaryDecodable {
        let response: String

        init(response: String) {
            self.response = response
        }

        func encode(to encoder: BinaryEncoder) throws {
            var container = encoder.container()
            try container.encode(response, encoding: .utf8, terminator: 0)
        }

        init(from decoder: BinaryDecoder) throws {
            var container = decoder.container(maxLength: nil)
            response = try container.decodeString(encoding: .utf8, terminator: 0)
        }
    }
    struct BeToLowerCodableRequest: BinaryEncodable, BinaryDecodable {
        let arg0: String

        init(arg0: String) {
            self.arg0 = arg0
        }

        func encode(to encoder: BinaryEncoder) throws {
            var container = encoder.container()
            try container.encode(arg0, encoding: .utf8, terminator: 0)
        }

        init(from decoder: BinaryDecoder) throws {
            var container = decoder.container(maxLength: nil)
            arg0 = try container.decodeString(encoding: .utf8, terminator: 0)
        }
    }
    struct BeTestDelayedReturnCodableResponse: BinaryEncodable, BinaryDecodable {
        let response0: String

        init(response0: String) {
             self.response0 = response0
        }

        func encode(to encoder: BinaryEncoder) throws {
            var container = encoder.container()
            try container.encode(response0, encoding: .utf8, terminator: 0)
        }

        init(from decoder: BinaryDecoder) throws {
            var container = decoder.container(maxLength: nil)
            response0 = try container.decodeString(encoding: .utf8, terminator: 0)
        }
    }
    struct BeTestDelayedReturnCodableRequest: BinaryEncodable, BinaryDecodable {
        let arg0: String

        init(arg0: String) {
            self.arg0 = arg0
        }

        func encode(to encoder: BinaryEncoder) throws {
            var container = encoder.container()
            try container.encode(arg0, encoding: .utf8, terminator: 0)
        }

        init(from decoder: BinaryDecoder) throws {
            var container = decoder.container(maxLength: nil)
            arg0 = try container.decodeString(encoding: .utf8, terminator: 0)
        }
    }

    @discardableResult
    public func bePrintThreadName(_ sender: Actor, _ callback: @escaping (Int) -> Void) -> Self {
        unsafeSendToRemote("Echo", "bePrintThreadName", Data(), sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! BinaryDataDecoder().decode(BePrintThreadNameCodableResponse.self, from: $0)).response
            )
        }
        return self
    }
    @discardableResult
    public func bePrint(_ string: String ) -> Self {
        let msg = BePrintCodableRequest(arg0: string)
        // swiftlint:disable:next force_try
        let data = try! BinaryDataEncoder().encode(msg)
        unsafeSendToRemote("Echo", "bePrint", data, nil, nil)
        return self
    }
    @discardableResult
    public func beToLower(_ string: String,
                          _ sender: Actor,
                          _ callback: @escaping (String) -> Void ) -> Self {
        let msg = BeToLowerCodableRequest(arg0: string)
        // swiftlint:disable:next force_try
        let data = try! BinaryDataEncoder().encode(msg)
        unsafeSendToRemote("Echo", "beToLower", data, sender) {
            callback(
                // swiftlint:disable:next force_try
                (try! BinaryDataDecoder().decode(BeToLowerCodableResponse.self, from: $0).response)
            )
        }
        return self
    }
    @discardableResult
    public func beTestDelayedReturn(_ string: String,
                                    _ sender: Actor,
                                    _ callback: @escaping (String) -> Void ) -> Self {
        let msg = BeTestDelayedReturnCodableRequest(arg0: string)
        // swiftlint:disable:next force_try
        let data = try! BinaryDataEncoder().encode(msg)
        unsafeSendToRemote("Echo", "beTestDelayedReturn", data, sender) {
            // swiftlint:disable:next force_try
            let msg = try! BinaryDataDecoder().decode(BeTestDelayedReturnCodableResponse.self, from: $0)
            callback(
                msg.response0
            )
        }
        return self
    }

    public func unsafeRegisterAllBehaviors() {
        safeRegisterRemoteBehavior("bePrintThreadName") { [unowned self] (_) in
            // swiftlint:disable:next force_try
            return try! BinaryDataEncoder().encode(
                BePrintThreadNameCodableResponse(response: self._bePrintThreadName()))
        }
        safeRegisterRemoteBehavior("bePrint") { [unowned self] (data) in
            // swiftlint:disable:next force_try
            let msg = try! BinaryDataDecoder().decode(BePrintCodableRequest.self, from: data)
            self._bePrint(msg.arg0)
            return nil
        }
        safeRegisterRemoteBehavior("beToLower") { [unowned self] (data) in
            // swiftlint:disable:next force_try
            let msg = try! BinaryDataDecoder().decode(BeToLowerCodableRequest.self, from: data)
            let response = self._beToLower(msg.arg0)
            let boxedResponse = BeToLowerCodableResponse(response: response)
            // swiftlint:disable:next force_try
            return try! BinaryDataEncoder().encode(boxedResponse)
        }
        safeRegisterDelayedRemoteBehavior("beTestDelayedReturn") { [unowned self] (data, callback) in
            // swiftlint:disable:next force_try
            let msg = try! BinaryDataDecoder().decode(BeTestDelayedReturnCodableRequest.self, from: data)
            self._beTestDelayedReturn(msg.arg0) {
                callback(
                    // swiftlint:disable:next force_try
                    try! BinaryDataEncoder().encode(
                        BeTestDelayedReturnCodableResponse(
                            response0: $0
                        )
                    )
                )
            }
        }
    }
}
