
import XCTest
@testable import Flynn

class Echo: RemoteActor {
    private var count: Int = 0
    
    private func _bePrint(_ string: String) {
        print("on slave: '\(string)'")
    }
    
    private func _beToLower(_ string: String) -> Data {
        count += 1
        if let data = ("\(string) [\(count)]").lowercased().data(using:.utf8) {
            return data
        }
        return Data()
    }
}



// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Echo {

    struct bePrintMessage: Codable {
        let arg0: String
    }
    struct beToLowerMessage: Codable {
        let arg0: String
    }

    @discardableResult
    public func bePrint(_ string: String ) -> Self {
        let msg = bePrintMessage(arg0: string)
        if let data = try? JSONEncoder().encode(msg) {
            unsafeSendToRemote("Echo", "bePrint", data, nil, nil)
        } else {
            fatalError()
        }
        return self
    }
    @discardableResult
    public func beToLower(_ string: String,
                          _ sender: Actor,
                          _ callback: @escaping RemoteBehaviorReply ) -> Self {
        let msg = beToLowerMessage(arg0: string)
        if let data = try? JSONEncoder().encode(msg) {
            unsafeSendToRemote("Echo", "beToLower", data, sender, callback)
        } else {
            fatalError()
        }
        return self
    }

    func unsafeRegisterAllBehaviors() {
        safeRegisterRemoteBehavior("bePrint") { [unowned self] (data) in
            if let msg = try? JSONDecoder().decode(bePrintMessage.self, from: data) {
                self._bePrint(msg.arg0)
            }
            return nil
        }
        safeRegisterRemoteBehavior("beToLower") { [unowned self] (data) in
            if let msg = try? JSONDecoder().decode(beToLowerMessage.self, from: data) {
                return self._beToLower(msg.arg0)
            }
            return nil
        }
    }
}
