import XCTest
@testable import Flynn

class Nate: Actor {

    private func _beToLower(_ string: String) -> String {
        return string.lowercased()
    }

}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Nate {

    @discardableResult
    public func beToLower(_ string: String,
                          _ sender: Actor,
                          _ callback: @escaping ((String) -> Void)) -> Self {
        unsafeSend { [weak self] in
            let result = self!._beToLower(string)
            sender.unsafeSend { callback(result) }
        }
        return self
    }

}
