import XCTest

@testable import Flynn

class PassToMe: Actor {

    private func _beNone() {
        print("hello world with no arguments")
    }

    private func _beString(_ string: String) {
        print(string)
    }

    private func _beNSString (_ string: NSString) {
        print(string)
    }

}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension PassToMe {

    @discardableResult
    public func beNone() -> Self {
        unsafeSend(_beNone)
        return self
    }
    @discardableResult
    public func beString(_ string: String) -> Self {
        unsafeSend { self._beString(string) }
        return self
    }
    @discardableResult
    public func beNSString(_ string: NSString) -> Self {
        unsafeSend { self._beNSString(string) }
        return self
    }

}
