import XCTest
@testable import Flynn

protocol Viewable: Actor {

    @discardableResult
    func beRender() -> Self
}

extension Viewable {

    private func _beRender() {
        print("Viewable.render")
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Viewable {

    @discardableResult
    public func beRender() -> Self {
        unsafeSend(_beRender)
        return self
    }

}
